### PR TITLE
Use LF as line splitter, discard CR if before LF

### PR DESCRIPTION
**Pull request by kuggenhoffen**
## Status
**READY**

## Description
This is to fix passthrough functionality, when a new line is detected we need to strip whole CRLF if it exists, not only LF

### CODE REVIEW

**Comment by tommikas** [comment]
Seems like a reasonable change. Unittests fail though...

**Comment by kuggenhoffen** [comment]
Apparently someone who uses mac OS 9 or something wrote the unittests since they rely on \r being the line separator :)
I'll check how to fix.

**Comment by tommikas** [comment]
I think it may be a case of the unittests simply having been written to fit the implementation as it was.

**Comment by jupe** [comment]
Probably changing this line: https://github.com/ARMmbed/mbed-client-cli/blob/7220a6e33a1e50b3d59e27f2267168c573c1e6b5/test/Test.cpp#L82 could fix the tests..

**Comment by jupe** [comment]
@YifeiZuo01 could you double check that this doesn't break tests with clitest ?

**Comment by jupe** [comment]
seems that there is still some failed tests - need more fixes

**Comment by YifeiZuo01** [comment]
built binary based on commit `7384a07`, run clitest regression hw tests on windows and linux, passed.

**Comment by jupe** [comment]
for some reason old obsoleted and disabled Jenkins job was triggered - seems that it doesn't work anymore. New job instead seems to be good shape as expected (Required ones)

**Comment by jupe** [comment]
This seems to break backward compatibility in windows case where terminal (pytty eg) sends only `\r` . Maybe we should revert this PR. What do you think ?

**Comment by artokin** [comment]
Maybe this should be reverted as manual testing does not work anymore. 
cc: @verkkila

**Comment by tommikas** [comment]
putty can pretty easily be configured to send \r\n. Not sure about other terminal applications though.

**Comment by kuggenhoffen** [comment]
Maybe revert the `if (u_data == '\n') {` back to `if (u_data == '\r' || u_data == '\n') {` and change the first if inside `if (cmd.cursor > 0 && cmd.input[cmd.cursor-1] == '\r')` to `if (u_data == '\n' && cmd.cursor > 0 && cmd.input[cmd.cursor-1] == '\r')`

**Comment by jupe** [comment]
Check out #79

**Pull request merged**
